[GLOBAL]
pants_version = "2.12.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.black",
  "pants.backend.python.typecheck.mypy"
]

# [repl]
# shell = "ipython"

# [setup-py-generation]
# generate_setup_default = false

[anonymous-telemetry]
enabled = false

# [pytest]
# lockfile = "3rdparty/python/pytest.lock"
# version = "pytest>=7.0.0"
# extra_requirements.add = ["ipdb"]

# extra_requirements = [
#   "pytest-cov>=2.12,!=2.12.1,<3.1",
#   "setuptools",
#   "Sphinx",
# ]

[python]
enable_resolves = true

# Enable using the PEX lockfile format, which provides support for custom indexes, and
# improves performance for large repositories.
lockfile_generator = "pex"

# [python.resolves]
# python-default = "lockfile_path.txt" 

[source]
root_patterns = [
    "/src",
    "/",
]   
 
