[tool.black]
line-length = 79

# [tool.setuptools]
# packages = ["sphinxcontrib.cldomain", "sphinxcontrib.hyperspec"]
# package-dir = "."

# [tool.setuptools.packages.find]
# include = ["sphinxcontrib*"]
#exclude = ["my_package.tests*"]  # exclude packages matching these glob patterns (empty by default)
#namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

# [tool.setuptools.packages.find]
# where = ["."]  # list of folders that contain the packages (["."] by default)
# include = ["sphinxcontrib*"]  # package names should match these glob patterns (["*"] by default)
# #exclude = ["my_package.tests*"]  # exclude packages matching these glob patterns (empty by default)
# namespaces = false  # to disable scanning PEP 420 namespaces (true by default)
