python_sources()

python_tests(
    name="tests0",
    dependencies=[
        "//:lib",
        "sphinxcontrib/cldomain:lisp_lib",
        # "//:sphinxcontrib-cldomain"
        # "3rdparty/python#setuptools",
        # "3rdparty/python#Sphinx",
    ],
)
