name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        lisp: [sbcl-bin]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install qlot

          # Install dependencies, this is caching because later on we
          # will run a lot of things in parallel and Quicklisp can't
          # pull dependencies in parallel without race's
          ros -e '(ql:quickload (list "sb-introspect" "unix-opts" "cl-json" "alexandria" "closer-mop" "swank" "fiveam"))'

      - name: Test with pants
        run: |
          ./pants test ::

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          ./pants lint ::
